service: serverless-architecture-generator
frameworkVersion: "=1.34.1"

custom:
  requestLabelSnsArn: 'arn:aws:sns:eu-west-1:539106611526:serverless-architecture-dev-label-request-topic'
  responseLabelSqsArn: 'arn:aws:sqs:eu-west-1:539106611526:label-generate-response-queue'
  remover:
    buckets:
      - serverless-architecture-dev

provider:
  name: aws
  runtime: java8

  stage: dev
  region: eu-west-1
  tracing: true # enable tracing
  environment:

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - Ref: LabelBucket
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - Ref: LabelBucket
            - "/*"

    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

plugins:
  - serverless-plugin-tracing
  - serverless-s3-remover


package:
  artifact: ./build/distributions/serverless-architecture.zip


functions:
  create-label:
    handler: be.drissamri.printing.LabelGeneratorLambda
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ LabelRequestQueue, Arn ]
          batchSize: 1
    reservedConcurrency: 100


resources:
  Resources:
    LabelRequestQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: label-generate-request
    ### Add SQS Consumer to SNS Producer
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        TopicArn: ${self:custom.requestLabelSnsArn}
        Region: 'eu-west-1'
        Endpoint:
          Fn::GetAtt: [ LabelRequestQueue, Arn ]

    ### Allows SNS to trigger SQS
    SQSQueuePolicy:
      Type: 'AWS::SQS::QueuePolicy'
      Properties:
        Queues:
          - Ref:  LabelRequestQueue
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Principal: '*'
              Action: 'sqs:SendMessage'
              Resource:
                Fn::GetAtt: [ LabelRequestQueue, Arn ]
              Condition:
                ArnEquals:
                  aws:SourceArn: ${self:custom.requestLabelSnsArn}
    ### Allows Anonymous to trigger AWS SNS Publish
    SNSTopicPolicy:
      Type: 'AWS::SNS::TopicPolicy'
      Properties:
        Topics:
          - ${self:custom.requestLabelSnsArn}
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Principal: '*'
              Action: 'sns:Publish'
              Resource: ${self:custom.requestLabelSnsArn}

    ### Response events published
    SNSLabelResponse:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: label-generate-response-topic
        TopicName: ${self:service}-${self:provider.stage}-label-response-topic
    SNSSubscriptionResponse:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        TopicArn:
          Ref: SNSLabelResponse
        Region: 'eu-west-1'
        Endpoint: ${self:custom.responseLabelSqsArn}
    SNSTopicPolicyResponse:
      Type: 'AWS::SNS::TopicPolicy'
      Properties:
        Topics:
          - Ref: SNSLabelResponse
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            #     "Service": "s3.amazonaws.com"
            - Effect: 'Allow'
              Principal: '*'
              Action: 'sns:Publish'
              Resource:
                - Ref: SNSLabelResponse
              Condition:
                StringLike:
                  aws:SourceArn: "arn:aws:s3:*:*:serverless-architecture-dev"
    LabelBucket:
      Type: AWS::S3::Bucket
      DependsOn: SNSTopicPolicyResponse
      Properties:
        BucketName: serverless-architecture-dev
        NotificationConfiguration:
          TopicConfigurations:
            - Event: s3:ObjectCreated:*
              Topic: 'arn:aws:sns:eu-west-1:539106611526:serverless-architecture-generator-dev-label-response-topic'


    SQSQueuePolicyResponse:
      Type: 'AWS::SQS::QueuePolicy'
      Properties:
        Queues:
          - 'https://sqs.eu-west-1.amazonaws.com/539106611526/label-generate-response-queue'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Principal: '*'
              Action: 'sqs:SendMessage'
              Resource: ${self:custom.responseLabelSqsArn}
              Condition:
                ArnEquals:
                  aws:SourceArn:
                    - Ref: SNSLabelResponse
